#!/usr/bin/env python3
"""Regenerate VERIFICATION.md from the artefacts that were actually produced.

This file is GENERATED EVIDENCE: it is excluded from the no-unsourced-number
scan by rule, and it is the corpus other documents may cite. Every line is
derived from a file on disk, never typed by hand.
"""
from __future__ import annotations

import json
import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
MARKER = "<!-- generated by tools/write_verification.py: do not edit -->"


def _read(rel: str) -> dict:
    path = ROOT / rel
    if not path.exists():
        return {}
    return json.loads(path.read_text(encoding="utf-8"))


def _count_collected(path: str, cwd: pathlib.Path) -> int:
    """Count every test node pytest can collect at `path`, markers aside.

    Runs from `cwd` so each suite gets its own rootdir/conftest (the demo
    suite imports `app.*`, which only resolves from demo/). `-m ''` disables
    the ini marker filter so the count is the whole population, and the
    per-file "path: N" lines are summed — no total line is printed in -q mode.
    """
    result = subprocess.run(
        [sys.executable, "-m", "pytest", "--collect-only", "-q", "-p", "no:cacheprovider", "-m", "", path],
        cwd=cwd,
        check=False,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
    )
    text = result.stdout.decode("utf-8", "replace")
    per_file = re.findall(r"^\S+: (\d+)$", text, flags=re.M)
    if per_file:
        return sum(int(count) for count in per_file)
    match = re.search(r"(\d+) tests? collected", text)
    return int(match.group(1)) if match else 0


def main() -> int:
    artefact = _read("bob_session/testscope_report.json")
    disabled = _read("submissions/ablation/disabled.json")
    oracle = _read("bob_session/evidence/oracle.json")
    measurement = _read("submissions/measurement.json")
    scorecard = _read("submissions/scorecard.json")
    gate_evidence = _read("bob_session/evidence/gate_author.json")
    revisions = _read("bob_session/evidence/revisions.json")

    engine_tests = _count_collected("tests", ROOT)
    demo_tests = _count_collected("tests", ROOT / "demo")

    summary = artefact.get("summary", {})
    meta = artefact.get("run_metadata", {})
    measurement_core = {key: measurement.get(key) for key in ("truth_size", "selected", "structurally_reachable", "recall", "missed", "price_of_safety")}
    ablation = measurement.get("ablation") or {}

    lines = [
        MARKER,
        "",
        "# Verification record",
        "",
        "Every figure below is read from an artefact on disk by `tools/write_verification.py`.",
        "Reproduce with `./verify.sh`.",
        "",
        "## Revisions",
        "",
        f"- rev_a `{revisions.get('rev_a')}`",
        f"- rev_b `{revisions.get('rev_b')}` (the change under analysis)",
        f"- rev_c `{revisions.get('rev_c')}` (necessity control)",
        f"- rev_d `{revisions.get('rev_d')}` (sensitivity control)",
        "",
        "## Suites",
        "",
        f"- engine suite: {engine_tests} tests collected under `tests/`",
        f"- demo suite: {demo_tests} test nodes collected under `demo/tests/`",
        f"- inventory rows: {meta.get('total_tests_in_suite')}",
        "",
        "## The ledger artefact",
        "",
        f"- digest: `{measurement.get('artefact_digest')}`",
        f"- selected {summary.get('selected_for_run')} of {summary.get('total')} "
        f"({summary.get('reduction_pct')}% reduction)",
        f"- structural {summary.get('definitely_affected_count')}, semantic {summary.get('semantically_affected_count')}, "
        f"stale {summary.get('stale_count')}, newly relevant {summary.get('newly_relevant_count')}, "
        f"uncovered {summary.get('uncovered_count')}, valid {summary.get('valid_count')}",
        f"- model layer: {meta.get('model_layer')} ({meta.get('model_status')}), coverage {meta.get('model_coverage')}, "
        f"coins recorded {meta.get('coins_spent')}",
        f"- diff files: {', '.join(meta.get('diff_files', []))}",
        f"- inert symbols: {', '.join(meta.get('inert_symbols', []))}",
        f"- changed symbols: {', '.join(meta.get('changed_symbols', []))}",
        "",
        "## Oracle (executed ground truth)",
        "",
        f"- collected {oracle.get('collected')} of {oracle.get('inventory_total')}, complete={oracle.get('complete')}",
        f"- changed (discriminating) {len(oracle.get('changed', []))}",
        f"- already red {len(oracle.get('already_red', []))}, flaky excluded {oracle.get('flaky_excluded_count')}, "
        f"missing {len(oracle.get('missing', []))}, unmapped {len(oracle.get('unmapped', []))}",
        f"- repeats per revision: {oracle.get('repeats')}, markers: {oracle.get('markers')}",
        "",
        "## Measurement",
        "",
        f"- truth_size {measurement_core['truth_size']}, selected {measurement_core['selected']}, "
        f"structurally_reachable {measurement_core['structurally_reachable']}",
        f"- recall {measurement_core['recall']}, missed {measurement_core['missed']}, "
        f"price_of_safety {measurement_core['price_of_safety']}",
        f"- ablation: disabled {ablation.get('disabled_recall')} -> enabled {ablation.get('enabled_recall')} "
        f"(delta {ablation.get('delta')}), additional true positives {ablation.get('additional_true_positives')}, "
        f"coins {ablation.get('coins_spent')}, coins per additional true positive "
        f"{ablation.get('coins_per_additional_true_positive')}",
        f"- baseline assertions: {[a.get('passed') for a in ablation.get('assertions', [])]}",
        f"- artefact with the model layer disabled: selected {disabled.get('summary', {}).get('selected_for_run')}, "
        f"recall {disabled.get('measurement', {}).get('recall')}",
        "",
        "## Gate G1..G5 (authored test)",
        "",
        f"- G1 buildable {gate_evidence.get('g1_buildable')}, G2 passes 5x {gate_evidence.get('g2_passes_5x')} "
        f"{gate_evidence.get('g2_runs')}",
        f"- G3 assertion fires at the base revision {gate_evidence.get('g3_assertion_fires_at_a')} "
        f"(origin {gate_evidence.get('g3_failure_origin')})",
        f"- G4 mutation strength {gate_evidence.get('g4_mutation_strength')} "
        f"({gate_evidence.get('g4_mutants_killed')}/{gate_evidence.get('g4_mutants_total')} mutants killed)",
        f"- G5 spec anchored {gate_evidence.get('g5_spec_anchored')}, capability {gate_evidence.get('capability')}",
        f"- accepted {gate_evidence.get('accepted')}: {gate_evidence.get('detail')}",
        "",
        "## Scorecard",
        "",
        f"- {scorecard.get('passed')}/{scorecard.get('total')} gates pass, each observed to fail once when corrupted",
        "",
        "| key | pass | observed to fail |",
        "|---|---|---|",
    ]
    for row in scorecard.get("rows", []):
        lines.append(f"| {row['key']} | {'PASS' if row['passed'] else 'FAIL'} | {'yes' if row['observed_fail'] else 'NO'} |")

    lines += [
        "",
        "## Reproduce",
        "",
        "```bash",
        "PYTHON=/path/to/python ./verify.sh",
        "```",
        "",
    ]
    (ROOT / "VERIFICATION.md").write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote VERIFICATION.md ({engine_tests} engine tests, {demo_tests} demo nodes, "
          f"scorecard {scorecard.get('passed')}/{scorecard.get('total')})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
